# Kubernetes configuration for the Clearly Defined crawler.
# (includes Redis dependency)
#
# Exposes crawler API on port 5000
#
# Replace all occurences of <configure me> with proper values before using.
#
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - name: crawler
          image: clearlydefined/crawler:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
            # These don't all need to be secrets, but this way lets us
            # be consistent and keep things in one place.
          env:
            - name: CRAWLER_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_NAME
            - name: CRAWLER_QUEUE_PREFIX
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_QUEUE_PREFIX
            - name: CRAWLER_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_WEBHOOK_URL
            - name: CRAWLER_AZBLOB_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_AZBLOB_CONTAINER_NAME
            - name: CRAWLER_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_GITHUB_TOKEN
            - name: CRAWLER_INSIGHTS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_INSIGHTS_KEY
            - name: CRAWLER_WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_WEBHOOK_TOKEN
            - name: CRAWLER_AZBLOB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CRAWLER_AZBLOB_CONNECTION_STRING
  selector:
    matchLabels:
      app: crawler
---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: crawler

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: redis
