# This workflow will build a docker image, push it to ghcr.io, and deploy it to an Azure WebApp.
name: Build and Deploy to dev crawler app

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    uses: clearlydefined/operations/.github/workflows/app-build-and-deploy.yml@v1.0.0
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      PRODUCTION_DEPLOYERS: ${{ secrets.PRODUCTION_DEPLOYERS }}
    with:
      deploy-env: dev
      application-type: worker
      azure-app-base-name: cdcrawler
      azure-app-name-postfix: -dev
